@Echo OFF

rem May want to do this non-recursively if we want to take up less space, due to how many automatic playlists are generated by our system


call validate-environment-variables MP3OFFICIAL DROPBOX

set MYTARGET=%DROPBOX%\BACKUPS\MP3\lists

set   SYNCSOURCE=%MP3OFFICIAL%\lists\
set   SYNCTARGET=%MYTARGET%
set      CLEANUP=%MYTARGET%
set   SYNCTRIGER=__ last synced to dropbox __   
call  sync-a-folder-to-somewhere.bat 

            

:::: some cleanup
    %CLEANUP%\
    sweep if exist attributes.dat (*del attributes.dat)
    sweep if exist attributes.dat (*del     genres.dat)
    sweep if exist attributes.dat (*del     datess.dat)
    sweep if exist attributes.dat (*del      files.dat)
    sweep if exist indexer.log    (*del    indexer.log)
    
